name: Compile LaTeX projects

on:
  push:
    paths:
      - "Tareas/T3/**"
      - "Tareas/T5/**"
      - "Tareas/T7/**"
      - "Tareas/T8/**"
      - "Tareas/T9/**"
  workflow_dispatch:

jobs:
  build-tarea-3:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T3
      tex_name: main
      out_name: "Tarea3"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  build-tarea-5:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T5
      tex_name: main
      out_name: "Tarea5"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  build-tarea-7:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T7
      tex_name: main
      out_name: "Tarea7"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  build-tarea-8:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T8
      tex_name: main
      out_name: "Tarea8"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  build-tarea-9:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T9
      tex_name: main
      out_name: "Tarea9"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit

  build-tarea-10:
    uses: MarcosLopezM/latex-workflow/.github/workflows/build-pdf.yml@main
    with:
      relative_path: Tareas/T10
      tex_name: main
      out_name: "Tarea10"
      # send_it: true
      email_to: "marcoslm@ciencias.unam.mx"
    secrets: inherit
